### PR TITLE
Dwarfs expected checks and HashBuild fixes

### PR DESCRIPTION
**Pull request by bagrorg**
This module is **not** for unit testing, but to centrally launch `dwarfs` and check that everything executes and works as it should (as far as possible) by checking the `valid` flag

### CODE REVIEW

**Comment by kurapov-peter** [comment]
Should this one be merged before #35 ?

**Comment by bagrorg** [comment]
> Should this one be merged before #35 ?

Yes, #35 is not ready yet

**Comment by bagrorg** [comment]
Also, I seem to have coped with the errors described in #6 and #22

**Comment by kurapov-peter** [comment]
> Also, I seem to have coped with the errors described in #6 and #22

Awesome! I'll have a look

**Review by kurapov-peter — APPROVED** [review]
Could you please fix EOFs? LGTM otherwise

**Review by kurapov-peter — APPROVED** [review]

**Pull request merged**
